using System.ComponentModel.DataAnnotations;

namespace HungryHelper.Data.Entities
{
    public class IngredientEntity
    {
        [Key]
        public int Id {get; set;} //will be generated automatically 
        [Required]
        [MaxLength(100)]
        public string Name {get; set;} //will be generated by user input
    }
}